version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: radius_db
      MYSQL_USER: radius
      MYSQL_PASSWORD: radiuspassword
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/tmp/init.sql
      - mysql_data:/var/lib/mysql  
    networks:
      - freeradius-docker_radiusnet

  freeradius:
    build: .
    depends_on:
      - mysql
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    networks:
      - freeradius-docker_radiusnet
      
networks:
  freeradius-docker_radiusnet:
    driver: bridge

volumes:
  mysql_data: